- name: install Nginx
  hosts: Web
  become: yes
  tasks:
  - name: install ngnix if RedHat
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat"  
  - name: install ngnix if Ubuntu
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"  
